% Compute upward velcoity of hip
function y_velocity = ...
    get_y_velocity(theta1,theta2_unshift,z_1_dot,...
    z_2_dot,L_1,L_2,Tdot1,Tdot2)

    y_velocity = (L_1.*cos(theta1(:,1)).*Tdot1.*z_1_dot+...
             L_2.*cos(theta1+theta2_unshift+pi).*Tdot1.*z_1_dot...
             +L_2.*cos(theta1+theta2_unshift+pi).*Tdot2.*z_2_dot);


end 