% Compute F' via for the equation
% F' = (L^{-T}*M*L^{-1})*z_double_dot + b(theta,theta_dot)
function [Linv_M_Linv, F_b_components_no_compliance] = ...
    get_F_components_no_compliance(H11, H22, H12, H21, h, G1, G2,...
    theta1, theta2_unshift, r1, r2, theta_dot1, theta_dot2)

% (L^{-T}*M*L^{-1})
Linv_M_Linv = [((H11/r1^2)), H12/(r1*r2);...
                H21/(r1*r2),(H22/r2^2)];

% b(theta,theta_dot)
b_component1 = (-(H11*theta_dot1^2)/(r1^2)*get_dr_dtheta1(theta1)...
        -(H12*theta_dot2^2)/(r1*r2)*get_dr_dtheta2(theta2_unshift)...
        -(h*theta_dot2^2)/r1- 2*h*theta_dot1*theta_dot2/r1...
        +G1/r1);
b_component2 = (-(H22*theta_dot2^2)/(r2^2)*get_dr_dtheta2(theta2_unshift)...
        -(H21*theta_dot1^2)/(r1*r2)*get_dr_dtheta1(theta1)... 
        +(h*theta_dot1^2)/r2+G2/r2);
[F_b_components_no_compliance] = [b_component1;b_component2];

end 